<?php

namespace Database\Seeders;

use App\Models\Measure;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MeasureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $values = array(
            [
                'measure_cat' => 'ASHP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Air Source Heat Pump not installed as per MCS Standards MIS 3005, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'BB', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'BIOM', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Biomass system not installed as per MCS Standards MIS 3004, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'BOILER', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'BR', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'COMP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Heating Controls',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'CWI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Cavity Wall Insulation',
                'cert_remediation_advice' => 'Cavity wall insulation not installed as per PAS2030 Annex B1, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'DG', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Window Glazing',
                'cert_remediation_advice' => 'Energy efficient glazing, doors and /or replacement units not installed as per PAS2030 Annex B3, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16. ',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'DP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Draught Proofing',
                'cert_remediation_advice' => 'Draught proofing not installed as per PAS2030 Annex B2, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'ESH', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Storage Heaters',
                'cert_remediation_advice' => 'Electric storage heaters not installed as per PAS2030 Annex D1, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'ESHR', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Storage Heaters',
                'cert_remediation_advice' => 'Electric storage heaters not installed as per PAS2030 Annex D1, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'EWI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for External Wall Insulation',
                'cert_remediation_advice' => 'External wall insulation not installed as per PAS2030 Annex B4, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'FCH', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'FRI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Flat Roof Insulation',
                'cert_remediation_advice' => 'Flat roof insulation not installed as per PAS2030 Annex B5, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'FTCH', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'GSHP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Ground Source Heat Pump not installed as per MCS Standards MIS 3005, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'H_CONT', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Heating Controls',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'HC', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Heating Controls',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'HHP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), MIS 3005, Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'HPED', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Draught Proofing',
                'cert_remediation_advice' => 'Energy efficient glazing, doors and /or replacement units not installed as per PAS2030 Annex B3, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16. ',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'HWI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for External Wall Insulation ATMA Competence for Internal Wall Insulation',
                'cert_remediation_advice' => 'External wall insulation not installed as per PAS2030 Annex B4, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16 and/or Internal wall insulation not installed as per PAS2030 Annex B8, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16 and BEIS Guide to Best Practice Retrofit Internal Wall Insulation.',
                'measure_min_qual' => 'N/A',
            'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'IWI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Internal Wall Insulation',
                'cert_remediation_advice' => 'Internal wall insulation not installed as per PAS2030 Annex B8, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16 and BEIS Guide to Best Practice Retrofit Internal Wall Insulation.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'LI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Loft Insulation',
                'cert_remediation_advice' => 'Loft insulation not installed as per PAS2030 Annex B9, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16 and General Requirements and Guidance for the Installation of Loft Insulation.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'NB', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Gas, LPG or Oil Heating measure not installed as per appropriate PAS2030 Annex (C1 or C2), Manufactureâ€™s instructions, Gas Safe, OFTEC and Electrical Wiring Regulations, documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'NESH', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Storage Heaters',
                'cert_remediation_advice' => 'Electric storage heaters not installed as per PAS2030 Annex D1, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'PHI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for External Wall Insulation ATMA Competence for Underfloor Insulation ATMA Compet',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
            'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'PRI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Loft Insulation',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'PWI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Cavity Wall Insulation',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'RIRI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Room in Roof Insulation',
                'cert_remediation_advice' => 'Room in roof insulation not installed as per PAS2030 Annex B12, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'S_PV', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Solar PV',
                'cert_remediation_advice' => 'Solar PV not installed as per MCS Standards MIS 3002, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'S_THERM', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Solar Thermal not installed as per MCS Standards MIS 3001, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'SMT', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Heating Controls',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'SP', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Solar PV',
                'cert_remediation_advice' => 'Solar PV not installed as per MCS Standards MIS 3002, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'ST', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Boilers',
                'cert_remediation_advice' => 'Solar Thermal not installed as per MCS Standards MIS 3001, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'TRV', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Heating Controls',
                'cert_remediation_advice' => 'Refer to Retrofit coordinator or scheme provider',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'UFI', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Underfloor Insulation',
                'cert_remediation_advice' => 'Floor insulation not installed as per PAS2030 Annex B6, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16 and BEIS Guide to Best Practice Retrofit Floor Insulation â€“ Suspended Timber Floors.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'WG', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Window Glazing',
                'cert_remediation_advice' => 'Energy efficient glazing, doors and /or replacement units not installed as per PAS2030 Annex B3, system or product supplier guidance (where provided), documents referenced in PAS2030 Section 10 and PAS2035 Section 16. ',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
            [
                'measure_cat' => 'SPV', 
                'cert_required' => '0',
                'cert_description' => 'ATMA Competence for Solar PV',
                'cert_remediation_advice' => 'Solar PV not installed as per MCS Standards MIS 3002, Manufactures Instructions, Electrical Wiring Regulations and relevant British Standards.',
                'measure_min_qual' => 'N/A',
                'measure_duration' => '15',
            ],
        );

        foreach ($values as $value) {
            Measure::create([
                'measure_cat' => $value['measure_cat'],
                'cert_required' => $value['cert_required'],
                'cert_description' => $value['cert_description'],
                'cert_remediation_advice' => $value['cert_remediation_advice'],
                'measure_min_qual' => $value['measure_min_qual'],
                'measure_duration' => $value['measure_duration'],
            ]);
        }
    }
}
