<?php

namespace Database\Seeders;

use App\Models\Navigation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NavigationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $values = [
            [
                'id' => 1,
                'name' => 'Dashboard',
                'link' => 'dashboard',
                'icon' => 'home',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 2,
                'name' => 'Installer Dashboard',
                'link' => 'installer-dashboard',
                'icon' => 'home',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 3,
                'name' => 'Manage Jobs',
                'link' => 'job',
                'icon' => 'briefcase',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 4,
                'name' => 'Open NC',
                'link' => 'open-nc',
                'icon' => 'th',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 5,
                'name' => 'Exceptions',
                'link' => '',
                'icon' => 'tachometer-alt',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 6,
                'name' => 'Property Inspector Exceptions',
                'link' => 'property-inspector-exception',
                'icon' => 'exclamation',
                'has_dropdown' => 0,
                'parent_id' => 5,
            ],
            [
                'id' => 7,
                'name' => 'Data Validation Exceptions',
                'link' => 'data-validation-exception',
                'icon' => 'exclamation',
                'has_dropdown' => 0,
                'parent_id' => 5,
            ],
            [
                'id' => 8,
                'name' => 'Document Exceptions',
                'link' => 'document-exception',
                'icon' => 'exclamation',
                'has_dropdown' => 0,
                'parent_id' => 5,
            ],
            [
                'id' => 9,
                'name' => 'Booking Exceptions',
                'link' => 'booking-exception',
                'icon' => 'exclamation',
                'has_dropdown' => 0,
                'parent_id' => 5,
            ],
            [
                'id' => 10,
                'name' => 'Remove Jobs',
                'link' => 'remove-job-exception',
                'icon' => 'exclamation',
                'has_dropdown' => 0,
                'parent_id' => 5,
            ],
            [
                'id' => 11,
                'name' => 'Platform Configuration',
                'link' => '',
                'icon' => 'cogs',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 12,
                'name' => 'Client Configuration',
                'link' => 'client-configuration',
                'icon' => 'handshake',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 13,
                'name' => 'User Configuration',
                'link' => 'user-configuration',
                'icon' => 'user',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 14,
                'name' => 'User Profile Configuration',
                'link' => 'user-profile-configuration',
                'icon' => 'users',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 15,
                'name' => 'Measure Configuration',
                'link' => 'measure',
                'icon' => 'ruler',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 16,
                'name' => 'Property Inspector Configuration',
                'link' => 'property-inspector',
                'icon' => 'user-secret',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 17,
                'name' => 'Scheme Configuration',
                'link' => 'scheme',
                'icon' => 'file',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 18,
                'name' => 'Survey Question Set',
                'link' => 'survey-question-set',
                'icon' => 'clipboard',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 19,
                'name' => 'Installer Configuration',
                'link' => 'installer-configuration',
                'icon' => 'user-tie',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
            [
                'id' => 20,
                'name' => 'Email Templates',
                'link' => '',
                'icon' => 'globe-asia',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 21,
                'name' => 'PI Email Template',
                'link' => 'pi-email-template',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 22,
                'name' => 'Uphold Email Template',
                'link' => 'uphold-email-template',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 23,
                'name' => 'Remediation Template',
                'link' => 'remediation-template',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 24,
                'name' => 'First Template',
                'link' => 'first-template',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 25,
                'name' => 'Second Template',
                'link' => 'second-template',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 26,
                'name' => 'Automated Email Passed',
                'link' => 'automated-email-passed',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 27,
                'name' => 'Bookings',
                'link' => '',
                'icon' => 'book',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 28,
                'name' => 'Make Booking',
                'link' => 'make-booking',
                'icon' => 'list',
                'has_dropdown' => 0,
                'parent_id' => 27,
            ],
            [
                'id' => 29,
                'name' => 'Manage Bookings',
                'link' => 'manage-booking',
                'icon' => 'list',
                'has_dropdown' => 0,
                'parent_id' => 27,
            ],
            [
                'id' => 30,
                'name' => 'Restore Max Attempts',
                'link' => 'restore-max-attempts',
                'icon' => 'list',
                'has_dropdown' => 0,
                'parent_id' => 27,
            ],
            [
                'id' => 31,
                'name' => 'Remediation Process',
                'link' => '',
                'icon' => 'list-ol',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 32,
                'name' => 'Remediation Review',
                'link' => 'remediation-review',
                'icon' => 'wrench',
                'has_dropdown' => 0,
                'parent_id' => 31,
            ],
            [
                'id' => 33,
                'name' => 'Remediation Reinstate',
                'link' => 'remediation-reinstate',
                'icon' => 'wrench',
                'has_dropdown' => 0,
                'parent_id' => 31,
            ],
            [
                'id' => 34,
                'name' => 'Installer Portal',
                'link' => 'installer-portal',
                'icon' => 'user-tie',
                'has_dropdown' => 0,
                'parent_id' => 31,
            ],
            [
                'id' => 35,
                'name' => '28-Day Exceptions',
                'link' => 'reminder-exception',
                'icon' => 'calendar-week',
                'has_dropdown' => 0,
                'parent_id' => 31,
            ],
            [
                'id' => 36,
                'name' => 'Update Survey',
                'link' => 'update-survey',
                'icon' => 'chart-pie',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 37,
                'name' => 'Reports',
                'link' => 'reports',
                'icon' => 'chart-pie',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 38,
                'name' => 'Accounts',
                'link' => '',
                'icon' => 'users',
                'has_dropdown' => 1,
                'parent_id' => '',
            ],
            [
                'id' => 39,
                'name' => 'Account Reconciliation',
                'link' => '',
                'icon' => 'angle-right',
                'has_dropdown' => 0,
                'parent_id' => 38,
            ],
            [
                'id' => 40,
                'name' => 'PI Dashboard',
                'link' => 'pi-dashboard',
                'icon' => 'briefcase',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 41,
                'name' => 'PI Sickness & Holidays',
                'link' => 'sickness-holidays',
                'icon' => 'notes-medical',
                'has_dropdown' => 0,
                'parent_id' => '',
            ],
            [
                'id' => 42,
                'name' => '28-Day Chaser',
                'link' => 'reminder-chaser',
                'icon' => 'envelope',
                'has_dropdown' => 0,
                'parent_id' => 20,
            ],
            [
                'id' => 43,
                'name' => 'Navigation Audit Logs',
                'link' => 'navigation-audit-log',
                'icon' => 'history',
                'has_dropdown' => 0,
                'parent_id' => 11,
            ],
        ];

        foreach ($values as $value) {
            Navigation::create([
                'id' => $value['id'],
                'name' => $value['name'],
                'link' => $value['link'],
                'icon' => $value['icon'],
                'has_dropdown' => $value['has_dropdown'],
                'parent_id' => $value['parent_id'],
            ]);
        }
    }
}
