<?php

namespace Database\Seeders;

use App\Models\OutwardPostcode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OutwardPostcodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $values = array(
            ['name' => 'AB'],
            ['name' => 'AL'],
            ['name' => 'B'],
            ['name' => 'BA'],
            ['name' => 'BB'],
            ['name' => 'BD'],
            ['name' => 'BH'],
            ['name' => 'BL'],
            ['name' => 'BN'],
            ['name' => 'BR'],
            ['name' => 'BS'],
            ['name' => 'BT'],
            ['name' => 'CA'],
            ['name' => 'CB'],
            ['name' => 'CF'],
            ['name' => 'CH'],
            ['name' => 'CM'],
            ['name' => 'CO'],
            ['name' => 'CR'],
            ['name' => 'CT'],
            ['name' => 'CV'],
            ['name' => 'CW'],
            ['name' => 'DA'],
            ['name' => 'DD'],
            ['name' => 'DE'],
            ['name' => 'DG'],
            ['name' => 'DH'],
            ['name' => 'DL'],
            ['name' => 'DN'],
            ['name' => 'DT'],
            ['name' => 'DY'],
            ['name' => 'E'],
            ['name' => 'EC'],
            ['name' => 'EH'],
            ['name' => 'EN'],
            ['name' => 'EX'],
            ['name' => 'FK'],
            ['name' => 'FY'],
            ['name' => 'G'],
            ['name' => 'GL'],
            ['name' => 'GU'],
            ['name' => 'GY'],
            ['name' => 'HA'],
            ['name' => 'HD'],
            ['name' => 'HG'],
            ['name' => 'HP'],
            ['name' => 'HR'],
            ['name' => 'HS'],
            ['name' => 'HU'],
            ['name' => 'HX'],
            ['name' => 'IG'],
            ['name' => 'IM'],
            ['name' => 'IP'],
            ['name' => 'IV'],
            ['name' => 'JE'],
            ['name' => 'KA'],
            ['name' => 'KT'],
            ['name' => 'KW'],
            ['name' => 'KY'],
            ['name' => 'L'],
            ['name' => 'LA'],
            ['name' => 'LD'],
            ['name' => 'LE'],
            ['name' => 'LL'],
            ['name' => 'LN'],
            ['name' => 'LS'],
            ['name' => 'LU'],
            ['name' => 'M'],
            ['name' => 'ME'],
            ['name' => 'MK'],
            ['name' => 'ML'],
            ['name' => 'N'],
            ['name' => 'NE'],
            ['name' => 'NG'],
            ['name' => 'NN'],
            ['name' => 'NP'],
            ['name' => 'NR'],
            ['name' => 'NW'],
            ['name' => 'OL'],
            ['name' => 'OX'],
            ['name' => 'PA'],
            ['name' => 'PE'],
            ['name' => 'PH'],
            ['name' => 'PL'],
            ['name' => 'PO'],
            ['name' => 'PR'],
            ['name' => 'RG'],
            ['name' => 'RH'],
            ['name' => 'RM'],
            ['name' => 'S'],
            ['name' => 'SA'],
            ['name' => 'SE'],
            ['name' => 'SG'],
            ['name' => 'SK'],
            ['name' => 'SL'],
            ['name' => 'SM'],
            ['name' => 'SN'],
            ['name' => 'SO'],
            ['name' => 'SP'],
            ['name' => 'SR'],
            ['name' => 'SS'],
            ['name' => 'ST'],
            ['name' => 'SW'],
            ['name' => 'SY'],
            ['name' => 'TA'],
            ['name' => 'TD'],
            ['name' => 'TF'],
            ['name' => 'TN'],
            ['name' => 'TQ'],
            ['name' => 'TR'],
            ['name' => 'TS'],
            ['name' => 'TW'],
            ['name' => 'UB'],
            ['name' => 'W'],
            ['name' => 'WA'],
            ['name' => 'WC'],
            ['name' => 'WD'],
            ['name' => 'WF'],
            ['name' => 'WN'],
            ['name' => 'WR'],
            ['name' => 'WS'],
            ['name' => 'WV'],
            ['name' => 'YO'],
            ['name' => 'ZE'],
        );

        foreach ($values as $value) {
            OutwardPostcode::create([
                'name' => $value['name'],
            ]);
        }
    }
}
